/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.svrf.client.model;

import java.util.Objects;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * Gets or Sets Category
 */
@JsonAdapter(Category.Adapter.class)
public enum Category {
  
  FILTERS("Face Filters");

  private String value;

  Category(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static Category fromValue(String text) {
    for (Category b : Category.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<Category> {
    @Override
    public void write(final JsonWriter jsonWriter, final Category enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public Category read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return Category.fromValue(String.valueOf(value));
    }
  }
}

