/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.svrf.client.model;

import java.util.Objects;
import io.swagger.annotations.ApiModel;
import com.google.gson.annotations.SerializedName;

import java.io.IOException;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

/**
 * The type of the Media. This should influence the media controls displayed to the user.
 */
@JsonAdapter(MediaType.Adapter.class)
public enum MediaType {
  
  PHOTO("photo"),
  
  VIDEO("video"),
  
  _3D("3d");

  private String value;

  MediaType(String value) {
    this.value = value;
  }

  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  public static MediaType fromValue(String text) {
    for (MediaType b : MediaType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }

  public static class Adapter extends TypeAdapter<MediaType> {
    @Override
    public void write(final JsonWriter jsonWriter, final MediaType enumeration) throws IOException {
      jsonWriter.value(enumeration.getValue());
    }

    @Override
    public MediaType read(final JsonReader jsonReader) throws IOException {
      String value = jsonReader.nextString();
      return MediaType.fromValue(String.valueOf(value));
    }
  }
}

