/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.svrf.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.svrf.client.model.SuccessResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PaginationResponse
 */

public class PaginationResponse {
  @SerializedName("success")
  private Boolean success = null;

  @SerializedName("nextPageNum")
  private Integer nextPageNum = null;

  @SerializedName("pageNum")
  private Integer pageNum = null;

  public PaginationResponse success(Boolean success) {
    this.success = success;
    return this;
  }

   /**
   * If the request was successful
   * @return success
  **/
  @ApiModelProperty(example = "true", value = "If the request was successful")
  public Boolean isSuccess() {
    return success;
  }

  public void setSuccess(Boolean success) {
    this.success = success;
  }

  public PaginationResponse nextPageNum(Integer nextPageNum) {
    this.nextPageNum = nextPageNum;
    return this;
  }

   /**
   * The next page to query to see more results, whether or not the next page actually exists.
   * @return nextPageNum
  **/
  @ApiModelProperty(value = "The next page to query to see more results, whether or not the next page actually exists.")
  public Integer getNextPageNum() {
    return nextPageNum;
  }

  public void setNextPageNum(Integer nextPageNum) {
    this.nextPageNum = nextPageNum;
  }

  public PaginationResponse pageNum(Integer pageNum) {
    this.pageNum = pageNum;
    return this;
  }

   /**
   * The current page number
   * @return pageNum
  **/
  @ApiModelProperty(value = "The current page number")
  public Integer getPageNum() {
    return pageNum;
  }

  public void setPageNum(Integer pageNum) {
    this.pageNum = pageNum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginationResponse paginationResponse = (PaginationResponse) o;
    return Objects.equals(this.success, paginationResponse.success) &&
        Objects.equals(this.nextPageNum, paginationResponse.nextPageNum) &&
        Objects.equals(this.pageNum, paginationResponse.pageNum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(success, nextPageNum, pageNum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginationResponse {\n");
    
    sb.append("    success: ").append(toIndentedString(success)).append("\n");
    sb.append("    nextPageNum: ").append(toIndentedString(nextPageNum)).append("\n");
    sb.append("    pageNum: ").append(toIndentedString(pageNum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

