/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.svrf.client.api;

import com.svrf.client.ApiException;
import com.svrf.client.model.AuthResponse;
import com.svrf.client.model.Body;
import com.svrf.client.model.ErrorResponse;
import com.svrf.client.model.RateLimitResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AuthenticateApi
 */
@Ignore
public class AuthenticateApiTest {

    private final AuthenticateApi api = new AuthenticateApi();

    
    /**
     * Authenticate application
     *
     * Authenticate an application&#39;s SVRF API Key to retrieve an access token to the SVRF API.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void authenticateTest() throws ApiException {
        Body body = null;
        AuthResponse response = api.authenticate(body);

        // TODO: test validations
    }
    
}
