/*
 * SVRF API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@svrf.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.svrf.client.api;

import com.svrf.client.ApiException;
import com.svrf.client.model.ErrorResponse;
import com.svrf.client.model.MediaType;
import com.svrf.client.model.RateLimitResponse;
import com.svrf.client.model.SearchMediaResponse;
import com.svrf.client.model.SingleMediaResponse;
import com.svrf.client.model.TrendingResponse;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MediaApi
 */
@Ignore
public class MediaApiTest {

    private final MediaApi api = new MediaApi();

    
    /**
     * Media by ID Endpoint
     *
     * Fetch media by its ID.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getByIdTest() throws ApiException {
        String id = null;
        SingleMediaResponse response = api.getById(id);

        // TODO: test validations
    }
    
    /**
     * Trending Endpoint
     *
     * The SVRF Trending Endpoint provides your app or project with the hottest immersive content curated by real humans. The experiences returned mirror the [SVRF homepage](https://www.svrf.com), from timely cultural content to trending pop-culture references. The trending experiences are updated regularly to ensure users always get fresh updates of immersive content.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getTrendingTest() throws ApiException {
        List<MediaType> type = null;
        String stereoscopicType = null;
        String category = null;
        Integer size = null;
        Integer minimumWidth = null;
        Integer pageNum = null;
        Boolean isFaceFilter = null;
        Boolean hasBlendShapes = null;
        Boolean requiresBlendShapes = null;
        TrendingResponse response = api.getTrending(type, stereoscopicType, category, size, minimumWidth, pageNum, isFaceFilter, hasBlendShapes, requiresBlendShapes);

        // TODO: test validations
    }
    
    /**
     * Search Endpoint
     *
     * The SVRF Search Endpoint brings the power of immersive search found on [SVRF.com](https://www.svrf.com) to your app or project. SVRF&#39;s search engine enables your users to instantly find the immersive experience they&#39;re seeking. Content is sorted by the SVRF rating system, ensuring that the highest quality content and most prevalent search results are returned. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void searchTest() throws ApiException {
        String q = null;
        List<MediaType> type = null;
        String stereoscopicType = null;
        String category = null;
        Integer size = null;
        Integer minimumWidth = null;
        Integer pageNum = null;
        Boolean isFaceFilter = null;
        Boolean hasBlendShapes = null;
        Boolean requiresBlendShapes = null;
        SearchMediaResponse response = api.search(q, type, stereoscopicType, category, size, minimumWidth, pageNum, isFaceFilter, hasBlendShapes, requiresBlendShapes);

        // TODO: test validations
    }
    
}
